[build]
  command = "npm install --production && npm install -g @netlify/build"
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["axios"]
  included_files = ["netlify/functions/**"]

[[redirects]]
  from = "/api/all/tickers/*"
  to = "/.netlify/functions/get-pairs"
  status = 200
  force = true

[[headers]]
  for = "/api/all/tickers/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/json"
    Cache-Control = "public, max-age=300, s-maxage=300"
    X-Function-Origin = "netlify"

[dev]
  framework = "#static"
  targetPort = 8888
  autoLaunch = false
